server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time

      - regex:
          expression: "^/var/lib/docker/containers/(?P<container_id>[0-9a-f]{64})-json.log$"
          source: filename

      - regex:
          expression: "^(?P<image_name>(?:[^|]*[^|]))\\|(?P<container_name>(?:[^|]*[^|]))$"
          source: tag

      - timestamp:
          source: time
          format: RFC3339Nano

      - labels:
          container_id:
          image_name:
          container_name:
          stream:

      - output:
          source: log