apiVersion: v1
kind: Service
metadata:
  name: app-go-service
spec:
  type: NodePort
  selector:
    app: app-go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008