apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-apps-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: app-python.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-python-service
                port:
                  number: 8000
    - host: app-go.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-go-service
                port:
                  number: 8080